T3491 - Switch kernel to 1000hz
vyos/vyos-build pull request #162
Opened 2021-04-22 21:53 UTC by xrobau

Signed-Off-By: Rob Thomas <xrobau@gmail.com>

## Change Summary
Change kernel HZ from 250 to 1000

## Types of changes

 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
T3491

## Component(s) name

kernel

## Proposed changes
Switch kernel frequency to 1000hz from 250hz, as 250hz was a holdover from the P4-ish era. This allows much better throughput and PPS, and also aligns us with most other distros HZ settings.

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2021-04-23 06:16 UTC, c-po requested changes
Hi @xrobau,

this is the same as #161. Please ensure your commit has a valid headline. I took to opportunity to alter the headlines from #161 to match our [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) guidelines. It is also always a good idea to check a files history what other maintainers used as the commit headline.

This is nothing to make your life harder, this is to make our life easier in the future when we revise changes why certain things became as they are.

2021-04-23 07:23 UTC, xrobau commented
No, it's not the same, I think you mis-clicked on the diff:

```
CONFIG_HZ_250=y
# CONFIG_HZ_250 is not set
# CONFIG_HZ_300 is not set
# CONFIG_HZ_1000 is not set
CONFIG_HZ=250
CONFIG_HZ_1000=y
CONFIG_HZ=1000
```

2021-04-23 07:23 UTC, xrobau commented
Well that didn't work well. How about this? 
![image](https://user-images.githubusercontent.com/457798/115834502-a529f600-a458-11eb-88ff-9d5ffcfc5260.png)

2021-04-23 17:17 UTC, c-po commented
LGTM

My comment is not about the change itself, it is about the formal process of using a good commit message which helps us in the future. Can you please reword it?

2021-05-01 07:25 UTC, c-po commented
Implemented via https://github.com/vyos/vyos-build/commit/a1c4e49e90c041e61d26b04bd7df7a89a919d7ec

2021-05-01 07:25 UTC, closed without merging