Jenkins: builld dsc packages beside amd64 binaries
vyos/vyos-build pull request #232
Opened 2022-05-09 09:37 UTC by andriiandrieiev

## Change Summary

- Building source packages beside amd64 binaries by default (new buildCmd default)
- Source packages added to build artifacts
- Source packages are uploaded to reprepro as well

## Types of changes

 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

## Component(s) name

Jenkins libs: 
- buildPackage.groovy
- cloneAndBuild.groovy

## Proposed changes

Build and upload source packages (*.dsc + *.tar.gz) beside with binaries (*.deb) to improve reproducibility of assemblages. Added try-exceptions for packages that can not build debian sources.  
## How to test

Use Jenkins to build any vyos package with default buildPackage() call (90% of packages will be applicable).
Tested in local Jenkins+reprepro environment.
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2022-05-11 11:54 UTC, dmbaturin requested changes
Looks good to me, but I'd move some paths from hardcoded variables to environment variables.

2022-05-11 11:54 UTC, dmbaturin commented on vars/buildPackage.groovy
> +                        def VYOS_REPO_PATH = '/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/' + RELEASE
Do you think we could move these paths to the environment variable definitions rather than hardcode them?

2022-05-11 11:55 UTC, dmbaturin requested changes
Looks good to me, but I'd move some paths from hardcoded variables to environment variables.

2022-05-11 15:26 UTC, andriiandrieiev commented on vars/buildPackage.groovy
> +                        def VYOS_REPO_PATH = '/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/' + RELEASE
I collided with some number of hardcoded solutions while local Jenkins testing.  It's not a single nuance. Hence I propose to move these parts in another PR.
I can remember these hardcoded parts:

- user ids
- jenkins labels
- Address of repository
- repository path
- repository requirements (reprepro, ucron, specific reprepro settings, etc.)
- Repository usage as fact

Also I found some strange behavior in amr64 builds: toggle true/false option in build func call does not work it's always on, and I couldn't build it in Jenkins on arm64 RPI (ISO extraction fails in the end of ISO builds)

Summing up. I think that it's better to do another one PR which will eliminate hardcode and allows any VyOS user to use our Jenkinsfiles easily. Eventually there is should be created/updated corresponding user documentation.

2022-05-21 09:22 UTC, andamasov commented
@andriiandrieiev @dmbaturin, so what do we do with this?

2022-05-24 09:10 UTC, dmbaturin commented on vars/buildPackage.groovy
> +                        def VYOS_REPO_PATH = '/home/sentrium/web/dev.packages.vyos.net/public_html/repositories/' + RELEASE
Ok, let's merge it as is, but we need to make sure that a temporary solution with hardcoded URLs doesn't become permanent, as it often happens.

2022-05-24 09:10 UTC, merged