Fix builds from detached Git HEAD
vyos/vyos-build pull request #526
Opened 2024-03-11 11:12 UTC by sfinke0

## Change Summary

Hello everyone!

<details>
  <summary>Build commands:</summary>

```
    - git clone -b sagitta --single-branch https://github.com/vyos/vyos-build
    - git checkout 1.4.0-epa1
    - cd vyos-build
    - export VYOS_VERSION=1.4.0-epa1
    - make clean
    - |
      ./build-vyos-image iso \
        --architecture amd64 \
        --build-by xxxx \
        --build-type release \
        --build-comment "VyOS with packages ready for prometheus node exporter and ansible" \
        --version "${VYOS_VERSION}-rolling-$(date +%Y-%m-%d-%H-%M)" \
        --custom-package bmon \
        --custom-package htop \
        --custom-package git \
        --custom-package ansible

```

</details>

Last night I tried to build sagitta from `1.4.0-epa1` but it failed due to the following error message:
```
build/config
Could not retrieve information from git: HEAD is a detached symbolic reference as it points to 'bcac2eb1f9b49cc15ebda65838e5465543dbb9c6'
```

I looked further into it and found the issue https://github.com/gitpython-developers/GitPython/issues/633. Working in a detached HEAD, when trying to build from a tagged commit for example, we are not exactly on a branch and therefore `build-vyos-image` fails to determine the active branch. My fix checks if the current checked out commit ID matches an available git tag and if that's the case, `git_branch` will be the name of the tag. 

Keep in mind that detached HEADs unrelated to tags are still likely to fail.

While fixing I also adjusted some indentations.

Check it out and let me know what you think. I'm happy to receive feedback.

Thanks in advance!
Sebastian

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/Txxxx

## Component(s) name

## Proposed changes

## How to test

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-03-11 11:32 UTC, sever-sever commented
Read please https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md


### Prepare patch/commit

In a big system, such as VyOS, that is comprised of multiple components, it’s
impossible to keep track of all the changes and bugs/feature requests in one’s
head. We use a bugtracker named Phorge (formerly known Phabricator) for it (“issue tracker” would
be a better term, but this one stuck).

The information is used in three ways:

* Keep track of the progress (what we have already done in this branch and
  what  we still need to do).
* Prepare automatic release notes for upcoming releases
* Help future maintainers of VyOS (it could be you!) to find out why certain
  things have been changed in the codebase or why certain features have been
  added

To make this approach work, every change must be associated with a task number
(prefixed with **T**) and a component. If there is no bug report/feature
request for the changes you are going to make, you have to create a development portal
task first. Once there is an entry in the development portal, you should reference its id
in your commit message, as shown below:

* `ddclient: T1030: auto create runtime directories`
* `Jenkins: add current Git commit ID to build description`

If there is no [development portal](https://vyos.dev) reference in the
commits of your pull request, we have to ask you to amend the commit message.
Otherwise we will have to reject it.

2024-03-11 11:56 UTC, sfinke0 commented
Thanks. I created a phabricator task. I can also revert indentation changes if requested, as they don't belong to the actual issue.

2024-03-14 11:12 UTC, dmbaturin requested changes
Please remove the indentation change commit. I have nothing against the substance of the patch, but unrelated changes should not be in the same PR.

2024-03-14 12:10 UTC, sfinke0 commented
Thanks for your feedback. I removed the indentation commit.

2024-03-16 08:45 UTC, c-po approved these changes

2024-03-16 08:45 UTC, merged

2024-03-16 08:45 UTC, c-po commented
@MergifyIo backport sagitta