T6635: add policy.json to podman package
vyos/vyos-build pull request #730
Opened 2024-08-06 09:15 UTC by nvollmar

## Change Summary
Adds default policy.json for Podman

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
https://vyos.dev/T6635

## Component(s) name
container

## Proposed changes
Custom Podman package needs to provide /etc/containers/policy.json otherwise running containers fails.

## How to test
```
add container image adguard/adguardhome:v0.107.52
```

## Checklist:
- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-08-06 09:16 UTC, nvollmar commented
@c-po I tried to fix it, I tested the generated deb package contains the policy.json

2024-08-06 09:18 UTC, nvollmar commented
Once we upgrade to Podman 5 the policy.json can be removed and copied from the Podman sources instead.

2024-08-06 10:17 UTC, sever-sever approved these changes

2024-08-06 18:27 UTC, c-po requested changes
We should rather add the file to https://github.com/vyos/vyos-1x/tree/current/src/etc. Maybe there will be CLI command sin the future which will render the file.

2024-08-06 19:44 UTC, Crushable1278 commented
Folks, this isn't the right fix. The rolling .iso is broken due to podman missing the `golang-github-containers-common` dependency that was present previously, which provides the missing policy file. The dependencies of podman should be modified to include the missing dep rather than sourcing an arbitrary file.

```
--depends golang-github-containers-common
```

It was alleged in phabricator that sagitta is not impacted, but testing with a smoketest .iso will not exhibit this behavior as the golang package is sourced via vyos-1x-smoketest. Has a release type sagitta .iso been tested to confirm the issue is present there given the custom podman package in the sagitta branch suffers the same missing dependency?

2024-08-06 21:50 UTC, nvollmar commented
@Crushable1278 Thanks for the hint, I will update the PR.

2024-08-07 05:24 UTC, c-po commented
@Crushable1278 thank you for reaching out to us.

@nvollmar there is #729 adding another dependency. I will close this PR and add it to #729 to avoid upcoming merge conflicts.

Thanks again all of you

2024-08-07 05:24 UTC, closed without merging

2024-08-07 05:32 UTC, c-po commented
@nvollmar I preserved your commit and cherry-picked it to my PR to keep your contribution noted
https://github.com/vyos/vyos-build/pull/729/commits/7508677091abf2b9c92d9c5c393fb73bb5128aa8

2024-08-07 05:47 UTC, nvollmar commented
makes sense, thanks 👍