build: T6859: include EULA files in build type definitions
vyos/vyos-build pull request #833
Opened 2024-11-08 11:58 UTC by dmbaturin

## Change Summary

Include EULA files in build type definitions so that they don't need to be added in a separate CI step. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): Internal change.

## Related Task(s)

## Component(s) name

Build configs.

## Proposed changes

## How to test

Images build with `--build-type development` and `--build-type release` should have the correct EULA in `/usr/share/vyos/EULA`.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-build/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-11-12 08:47 UTC, c-po approved these changes

2024-11-12 09:26 UTC, sever-sever commented on data/build-types/release.toml
> +We doe not assert any Intellectual Property Rights over:
Typo `doe`

2024-11-17 11:31 UTC, c-po requested changes

2024-11-17 11:31 UTC, c-po commented on data/build-types/release.toml
> +We doe not assert any Intellectual Property Rights over:
```suggestion
We do not assert any Intellectual Property Rights over:
```

2024-11-20 19:45 UTC, c-po approved these changes

2024-11-20 19:46 UTC, c-po commented
After comiting the suggestion this one should be squashed and merged

2024-11-20 20:00 UTC, sever-sever approved these changes

2024-11-30 07:49 UTC, merged